### ISSUE TITLE
Provide gazebo plugins of animated box?

### ISSUE THREAD

**Issue by ZhenshengLee** [winstxnhdw/AutoCarROS2#2]
Thanks.

**Comment by winstxnhdw** [comment]
It's not a plugin.

Read http://wiki.ros.org/rviz/DisplayTypes/Marker and http://docs.ros.org/en/noetic/api/visualization_msgs/html/msg/MarkerArray.html

**Comment by ZhenshengLee** [comment]
@winstxnhdw Thanks for your reply.

> It's not a plugin. The preview in the README is a view in RViz, not Gazebo.

Animated box shown in RViz must be a dynamic obstacle provided by Gazebo, the model and behavior can be programmed and loaded as a gazebo plugin, am I right?

So if this mechinism of generation of dynamic obstacle in gazebo could be opensourced, it will be the true power.

**Comment by winstxnhdw** [comment]
I have never used any Gazebo plugin other than the standard ros-gazebo plugin. Dynamic obstacles and retrieval of obstacle state is all done within ROS.

**Comment by ZhenshengLee** [comment]
@winstxnhdw  OK, I misunderstand your simulation arch. 
So the dynamic obstacle info is not provided by gazebo's dynamic models(obstacles) but a programmed obstacle state info publisher.
That is why your simulation arch locks perception stack.
Am I right?

**Comment by winstxnhdw** [comment]
Yes. At the time, I wanted to focus more on the path planning approach which is why all 'perception' in my architecture is artificial.
