### ISSUE TITLE
Is the code you used to generate the gif on README part of the repo?

### ISSUE THREAD

**Issue by armuren** [winstxnhdw/AutoCarROS2#3]
Many thanks for this great work! It's given me a good idea on what I am trying to accomplish.

I am wondering if I have a problem in my setup or if you used a different repo to generate the gif in README.

When I launch the default_launch, the vehicle does move, however there are no obstacles visible in rviz, just the ground plane, and a gray area that represent the sensor zone.

![image](https://user-images.githubusercontent.com/2354387/184054331-4fb1477f-b51d-414d-9a82-fea18e552f0e.png)

There are no errors in the console, so I am curious if you've used a different simulation to generate that gif?

**Comment by winstxnhdw** [comment]
Hi @armuren 
This is not a mistake. The GIF in the README is generated from an **extension** of this repository. This repository is simply a **template** to start development from (as stated in the README). 

I am unable to open-source the code used to generate the GIF as it belongs to the company I used to work at. Hope you understand (:

**Comment by armuren** [comment]
thanks @winstxnhdw makes sense.  I thought so, just wanted to be sure.  Thanks again, this is a really good starting point for me.
