### ISSUE TITLE
Build error please help

### ISSUE THREAD

**Issue by Soumya-Saha** [winstxnhdw/AutoCarROS2#6]
Hi,

_/\_ Thanks a lot for the project. I am getting errors at the start of the colcon build. I am using Ubuntu 22 and ROS2 Humble.

I have attached the screenshots, will you please tell me what I should do? I installed all the dependencies and followed your instructions.

![colconerrors1](https://user-images.githubusercontent.com/10720664/200134852-93e230e2-c206-4e44-97a8-667a77cdaad6.png)
![colconerrors2](https://user-images.githubusercontent.com/10720664/200134866-382d6a77-291c-4d85-9be0-d55f153c1d3e.png)

**Comment by winstxnhdw** [comment]
Hi @Soumya-Saha,

I notice that you are using ROS2 Humble instead of ROS2 Foxy. Please note that ROS1/2 has never been forward/backwards compatible. If you want to build this project successfully, you will have to switch over to ROS2 Foxy.

**Comment by Soumya-Saha** [comment]
Ok, I see. Thanks for your reply!
