### ISSUE TITLE
Build error again please help!

### ISSUE THREAD

**Issue by Soumya-Saha** [winstxnhdw/AutoCarROS2#7]
Hi there again,

_/_ Thanks a lot for the project. I am getting errors at the start of the colcon build. This time I am using ROS2 Foxy with Ubuntu 20 as you instructed.

I have attached the screenshots, will you please tell me what I should do? I installed all the dependencies and followed your instructions.

![colconErrorAutocar3](https://user-images.githubusercontent.com/10720664/200180804-911b9ec0-ddea-4c33-8c53-326627a423a0.png)
![colconErrorAutocar2](https://user-images.githubusercontent.com/10720664/200180805-71218611-6051-4491-9ff2-1f13b9104efe.png)
![colconErrorAutocar](https://user-images.githubusercontent.com/10720664/200180806-12ed02cc-f7dd-45fe-82ab-5ab689825eac.png)

**Comment by winstxnhdw** [comment]
Hi @Soumya-Saha,

Are you sure you followed the instructions and sourced `setup.bash`?

```bash
source /opt/ros/foxy/setup.bash
```

**Comment by Soumya-Saha** [comment]
Yes, I redid everything. Now only this particular error is showing in all the packages.

![colconerrorcar2](https://user-images.githubusercontent.com/10720664/200298426-0812f83e-a27f-4052-9d40-6bf6fd258155.png)

**Comment by winstxnhdw** [comment]
@Soumya-Saha 

Your system is missing ament_cmake. Please look for any error messages during your install that could be preventing you from installing the dependency. Otherwise, try setting up a basic pubsub first and working from there. https://docs.ros.org/en/foxy/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Py-Publisher-And-Subscriber.html

**Comment by Soumya-Saha** [comment]
The error is still persisting. Tried to colcon build the beginner tutorial of "creating a workspace" and still the same ament_cmake error in the beginning of the build. Has it got to do anything with providing file permissions?

**Comment by winstxnhdw** [comment]
@Soumya-Saha 

There could be many reasons for this error. If you are on a fresh default Ubuntu 20 install on x86, there should be no issues for you, regardless of hardware. 

You need to be aware that the tutorial was made assuming the user has a fresh Ubuntu install. If you divert from this, you will require sufficient experience in Linux to troubleshoot. It can be anything from not using the bash shell, using a poorly setup terminal, or messing with the default file permissions. Unfortunately, I won't be able to help you if I don't have more information about your system.

**Comment by Soumya-Saha** [comment]
Yes. its a fresh Ubuntu 20 x64 install on my WindowsSubsystem on Windows 11.

**Comment by winstxnhdw** [comment]
@Soumya-Saha 

And there is your problem. You are on WSL. Please mention important details like that **first** next time. I am closing this issue.
