### ISSUE TITLE
gazebo won't launch

### ISSUE THREAD

**Issue by gustavosousa2208** [winstxnhdw/AutoCarROS2#8]
Sorry for the dumb question, but gazebo won't start in click_launch.py, and there's no obstacles in rviz with default_launch.py. Any tips for running the simulation?

**Comment by winstxnhdw** [comment]
Hey, please share the logs when launching `click_launch.py`. `default_launch.py` has no obstacles on default. You will have to change the world file to the populated worlds. See [here](https://github.com/winstxnhdw/AutoCarROS2/blob/master/launches/launch/default_launch.py#L17).

**Comment by gustavosousa2208** [comment]
[launch.log](https://github.com/winstxnhdw/AutoCarROS2/files/10974960/launch.log)
[console_out.txt](https://github.com/winstxnhdw/AutoCarROS2/files/10986692/console_out.txt)
Opening populated_road.world hangs gazebo

**Comment by winstxnhdw** [comment]
I have reviewed the logs you sent and noticed no abnormalities. My guess is that your Gazebo has not cached the 3D models yet. On the first launch, Gazebo may take up to 30 minutes to load. This applies to every world using the default Gazebo objects. If you are still getting this issue, try opening Gazebo standalone and placing an object in the world.

```bash
gazebo &
```
